# Generated by Django 4.1.4 on 2023-01-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tilte',
            new_name='title',
        ),
    ]
